# Generated by Django 5.1.4 on 2025-01-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="joined_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="phone",
            field=models.IntegerField(null=True),
        ),
    ]
